#!/usr/bin/env sh

THIS_DIR=$(realpath $(dirname $0))

/usr/bin/cmake --no-warn-unused-cli -DCMAKE_PROJECT_INCLUDE_BEFORE:STRING=$THIS_DIR/SetupHunter.cmake -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -DCMAKE_BUILD_TYPE:STRING=Debug -DCMAKE_C_COMPILER:FILEPATH=/bin/clang-10 -DCMAKE_CXX_COMPILER:FILEPATH=/bin/clang++-10 -H/home/raf/develop/cpp/algos -B/home/raf/develop/cpp/algos/build -G Ninja

/usr/bin/cmake --build $THIS_DIR/build --config Debug --target all -- -j 10

