name: C/C++ CI std
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, windows-2016]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Cache Hunter
      uses: actions/cache@v2
      env:
        cache-name: cache-hunter-std
      with:
        path: ~/.hunter/
        key: ${{ matrix.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/CMakeLists.txt') }}
        restore-keys: |
          ${{ matrix.os }}-build-${{ env.cache-name }}-
          ${{ matrix.os }}-build-
          ${{ matrix.os }}-
    
    - name: configure
      run: mkdir build && cd build && cmake ..

    - name: build
      run: cmake --build build --config Debug

    - name: test
      run: cd build && ctest
